
export const staticSuggestions = [
  'Bangalore, Karnataka', 'Hubli, Karnataka', 'Dharwad, Karnataka', 'Mysuru, Karnataka', 'Belagavi, Karnataka', 'Mangalore, Karnataka',
  'Gulbarga, Karnataka', 'Davanagere, Karnataka', 'Bellary, Karnataka', 'Bijapur, Karnataka', 'Shivamogga, Karnataka',
  'Tumkur, Karnataka', 'Raichur, Karnataka', 'Bidar, Karnataka', 'Hospet, Karnataka', 'Hassan, Karnataka',
  'Gadag-Betigeri, Karnataka', 'Chitradurga, Karnataka', 'Udupi, Karnataka', 'Robertsonpet, Karnataka', 'Bhadravati, Karnataka',
  'Haveri, Karnataka', 'Gangawati, Karnataka', 'Bagalkot, Karnataka', 'Yadgir, Karnataka', 'Karwar, Karnataka',
  'Chamarajanagar, Karnataka', 'Ramanagara, Karnataka', 'Gokak, Karnataka', 'Tiptur, Karnataka', 'Kolar, Karnataka',
  'Sandur, Karnataka', 'Athni, Karnataka', 'Gokarna, Karnataka', 'Arsikere, Karnataka', 'Navalgund, Karnataka',
  'Sindhnur, Karnataka', 'Sidlaghatta, Karnataka', 'Sedam, Karnataka', 'Shrirangapattana, Karnataka', 'Sira, Karnataka',
  'Puttur, Karnataka', 'Laxmeshwar, Karnataka', 'Malavalli, Karnataka', 'Madikeri, Karnataka', 'Mudhol, Karnataka',
  'Channarayapatna, Karnataka', 'Sirsi, Karnataka', 'Nipani, Karnataka', 'Kundapura, Karnataka', 'Tarikere, Karnataka',
  'Malur, Karnataka', 'Savanur, Karnataka', 'Sadalagi, Karnataka', 'Ron, Karnataka', 'Ranibennur, Karnataka',
  'Byadgi, Karnataka', 'Devanhalli, Karnataka', 'Humnabad, Karnataka', 'Nargund, Karnataka', 'Siddapur, Karnataka',
  'Muddebihal, Karnataka', 'Sankeshwara, Karnataka', 'Shahpur, Karnataka', 'Saundatti-Yellamma, Karnataka', 'Lingsugur, Karnataka',
  'Adyar, Karnataka', 'Pavagada, Karnataka', 'Malpe, Karnataka', 'Mulbagal, Karnataka', 'Wadi, Karnataka',
  'Manvi, Karnataka', 'Shiggaon, Karnataka', 'Lar, Karnataka', 'Rabkavi Banhatti, Karnataka', 'Yelbarga, Karnataka',
  'Basavana Bagevadi, Karnataka', 'Hangal, Karnataka', 'Nelamangala, Karnataka', 'Mudalagi, Karnataka', 'Ron, Karnataka',
  'Piriyapatna, Karnataka', 'Srinivaspur, Karnataka', 'Adityapatna, Karnataka', 'Yadgir, Karnataka', 'Bhatkal, Karnataka',
  'Navalgund, Karnataka', 'Sankeshwara, Karnataka', 'Shahpur, Karnataka', 'Saundatti-Yellamma, Karnataka', 'Lingsugur, Karnataka',
  'Adyar, Karnataka', 'Pavagada, Karnataka', 'Malpe, Karnataka', 'Mulbagal, Karnataka', 'Wadi, Karnataka',
  'Delhi, Delhi', 'Mumbai, Maharashtra', 'Kolkata, West Bengal', 'Chennai, Tamil Nadu', 'Hyderabad, Telangana',
  'Ahmedabad, Gujarat', 'Pune, Maharashtra', 'Surat, Gujarat', 'Jaipur, Rajasthan', 'Lucknow, Uttar Pradesh',
  'Kanpur, Uttar Pradesh', 'Nagpur, Maharashtra', 'Indore, Madhya Pradesh', 'Thane, Maharashtra', 'Bhopal, Madhya Pradesh',
  'Visakhapatnam, Andhra Pradesh', 'Pimpri-Chinchwad, Maharashtra', 'Patna, Bihar', 'Vadodara, Gujarat', 'Ghaziabad, Uttar Pradesh',
  'Ludhiana, Punjab', 'Agra, Uttar Pradesh', 'Nashik, Maharashtra', 'Faridabad, Haryana', 'Meerut, Uttar Pradesh',
  'Rajkot, Gujarat', 'Kalyan-Dombivli, Maharashtra', 'Vasai-Virar, Maharashtra', 'Varanasi, Uttar Pradesh', 'Srinagar, Jammu and Kashmir',
  'Aurangabad, Maharashtra', 'Dhanbad, Jharkhand', 'Amritsar, Punjab', 'Navi Mumbai, Maharashtra', 'Allahabad, Uttar Pradesh',
  'Ranchi, Jharkhand', 'Howrah, West Bengal', 'Coimbatore, Tamil Nadu', 'Jabalpur, Madhya Pradesh', 'Gwalior, Madhya Pradesh',
  'Vijayawada, Andhra Pradesh', 'Jodhpur, Rajasthan', 'Madurai, Tamil Nadu', 'Raipur, Chhattisgarh', 'Kota, Rajasthan',
  'Chandrapur, Maharashtra', 'Guwahati, Assam', 'Bhubaneswar, Odisha', 'Dehradun, Uttarakhand', 'Shimla, Himachal Pradesh',
  'Gangtok, Sikkim', 'Imphal, Manipur', 'Itanagar, Arunachal Pradesh', 'Kohima, Nagaland', 'Agartala, Tripura', 'Aizawl, Mizoram',
  'Panaji, Goa', 'Thiruvananthapuram, Kerala', 'Shillong, Meghalaya', 'Dispur, Assam', 'Chandigarh, Chandigarh', 'Raebareli, Uttar Pradesh',
  'Bareilly, Uttar Pradesh', 'Mysuru, Karnataka', 'Tirupati, Andhra Pradesh', 'Salem, Tamil Nadu', 'Warangal, Telangana',
  'Guntur, Andhra Pradesh', 'Rourkela, Odisha', 'Jalandhar, Punjab', 'Sangli, Maharashtra', 'Bhavnagar, Gujarat',
  'Bellary, Karnataka', 'Tuticorin, Tamil Nadu', 'Durgapur, West Bengal', 'Asansol, West Bengal', 'Nanded, Maharashtra',
  'Kollam, Kerala', 'Tirunelveli, Tamil Nadu', 'Ajmer, Rajasthan', 'Nellore, Andhra Pradesh', 'Ajmer, Rajasthan',
  'Kollam, Kerala', 'Bhiwandi, Maharashtra', 'Firozabad, Uttar Pradesh', 'Bilaspur, Chhattisgarh', 'Haldia, West Bengal',
  'Tiruvannamalai, Tamil Nadu', 'Ratlam, Madhya Pradesh', 'Haridwar, Uttarakhand', 'Sagar, Madhya Pradesh', 'Mathura, Uttar Pradesh',
  'Karnal, Haryana', 'Shimoga, Karnataka', 'Nizamabad, Telangana', 'Muzaffarpur, Bihar', 'Palakkad, Kerala',
  'Bijapur, Karnataka', 'Brahmapur, Odisha', 'Alwar, Rajasthan', 'Katihar, Bihar', 'Ambala, Haryana',
];


